name: WasteUtils
main: Main
version: 0.0.1 Demo
api-version: 1.19
authors: [ xiaodi001, mao_mao_shen, xianyu1145 ]
commands:
  test:
    description: to test that make sure WasteUtils is working
    usage: /test