name: WasteUtils
main: org.wasteutils.WasteUtils.Main
version: 0.0.1 Demo
api-version: 1.20
authors: [ xiaodi001,mao_mao_shen,xianyu1145 ]
softdepend:
  - Vault
commands:
  test:
    description: to test that make sure WasteUtils is working
    usage: "Hello world!"
  wasteutils:
    description: WasteUtils Admin setting
    aliases: [ wu, waste ]