name: WasteUtils
main: org.wasteutils.WasteUtils.Main
version: 0.0.5
api-version: 1.20
authors: [ xiaodi001,mao_mao_shen,xianyu1145 ]
commands:
  test:
    description: to test that make sure WasteUtils is working
    usage: "应该是跑起来了"
  wasteutils:
    description: WasteUtils Admin setting
    aliases: [ wu, waste ]
  matchmaking:
    description: Matchmaking components of WasteUtils
    aliases: [ mm, match ]
  economies:
    description: Wasteutils Economies module
    aliases: [ wueco, eco ]
  uid:
    description: view my uid
    aliases: [ id ]
  pd:
    description: View and join the community